#main.yml
name: Continuous Integration with Github Actions

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                  python-version: 3.11
            - name: Install dependencies
              run:
                  make install

            - name: Run tests
              run: make test
